### PR TITLE
import the correct go-stream-muxer repo

### PR DESCRIPTION
**Pull request by marten-seemann**
This currently breaks the build.

@whyrusleeping, @Stebalien.

### CODE REVIEW

**Comment by Stebalien** [comment]
Could you also update the gx dep and do a gx release?

**Comment by marten-seemann** [comment]
Done.

**Review by Stebalien — APPROVED** [review]
LGTM!

**Comment by Stebalien** [comment]
And this is one of those repos I don't have access to... Sorry, we'll have to wait for @whyrusleeping to come back.

**Comment by Kubuxu** [comment]
@whyrusleeping plz merge

**Pull request merged**
